# Excercise 2 - https://projecteuler.net/problem=2
'''
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''
fibonacci = [1,2]

# loop to max out the complete list
max_value = 4000000
while (fibonacci[-1] + fibonacci[-2]) < max_value:
    fibonacci.append (fibonacci[-1] + fibonacci[-2])

print('fibonacci : ', fibonacci)

# sum even valued items
sum_even_valued_items = 0
for num in fibonacci:
    if num % 2 == 0:
        sum_even_valued_items += num

print('sum_even_valued_items : ', sum_even_valued_items)
# Answer: 4613732